# Generated by Django 4.2.7 on 2024-10-07 22:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 22, 30, 48, 295041, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
