# Generated by Django 4.2.7 on 2024-10-07 22:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_calculation_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 7, 22, 34, 40, 795790, tzinfo=datetime.timezone.utc), verbose_name='Дата создания'),
        ),
    ]
